### ISSUE TITLE
The family tree is enable in the advancements screen.

### ISSUE THREAD

**Issue by Dig1t0** [Janschuri/LunaticFamily#27]
The family tree is enable in the advancements screen in paper 1.21.1. The config has been set to 'use_crazy_advancement_api: true'. Tried the last three versions of CrazyAdvancementsAPI and it didn't work.
The error is: Could not pass event PlayerJoinEvent to CrazyAdvancementsAPI v2.1.21
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R3/entity/CraftPlayer

**Comment by Janschuri** [comment]
It should work work with 2.1.19. Could you please provide me the full error?
